### PR TITLE
network: refactor some network functionality

### PR DESCRIPTION
**Pull request by Foxboron**
Related-to https://github.com/system-transparency/stboot/issues/66

Signed-off-by: Morten Linderud <morten.linderud@mullvad.net>

### CODE REVIEW

**Review by jenstopp — COMMENTED** [review]
:+1: 
Regarding host.Recover: 
We used to only call it on the top level and propagate errors otherwise.
Since recently, pkg `sterror` provides the E() function for that purpose

**Comment by jensdrenhaus** [comment]
Yes, that's ok for now, since I'd like to get your opinion on error handling / wrapping / sterror pkg.

**Comment by Foxboron** [comment]
The `stlog` error handling is a tiny bit weird. I'm not super sure when you want to make a new error, forward them or not :upside_down_face: I settled on a hybrid for this.

**Comment by jensdrenhaus** [comment]
@Foxboron, is this still relevant?

**Comment by Foxboron** [comment]
Partially, but it can be deferred until later I think. It's not a complicated change.

**Comment by jensdrenhaus** [comment]
I see, "relevant" was not the right term. It's not urgent, right?
I'll take that into account while refactoring once we are on GitLab.

**Comment by Foxboron** [comment]
Not urgent at all. It was me looking around the stboot code the first month :)

**Comment by jensdrenhaus** [comment]
https://git.glasklar.is/system-transparency/core/stboot/-/tree/main/

**Pull request closed without merging**
